### ISSUE TITLE
Need/want rbac_group resource

### ISSUE THREAD

**Issue by robinbowes** [puppetlabs/pltraining-rbac#4]
We have a need for an rbac_group resource. Is this anywhere in the pipeline, or do you need/want a PR?

R.

**Comment by binford2k** [comment]
We'll add this in the weeks after Conf. You're welcome to contribute if you'd like. Thanks!

**Comment by greglarkin** [comment]
See https://github.com/puppetlabs/pltraining-rbac/pull/20
